pine_studio/pine/urls.py
from django.urls import path
from .views.home import HomeView
from .views.pack import PackListView, PackDetailView
from .views.about import AboutPageView
from .views.contact import ContactView
from .views.webhook import MessengerWebhook

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('packs/', PackListView.as_view(), name='packs'),
    path('quem_sou_eu/', AboutPageView.as_view(), name='about'),
    path('contato/', ContactView.as_view(), name='contact'),
    path('<slug:slug>/', PackDetailView.as_view(), name='pack_detail'),
]

pine_studio/pine_studio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pine.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pine_studio/pine/models/contact.py
from django.db import models
from ._base import BaseModel


class ContactMessage(BaseModel):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15, blank=True, null=True) 
    subject = models.CharField(max_length=200, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

pine_studio/pine/models/download_email.py
from django.db import models
from ..models._base import BaseModel
from ..models.pack import Pack


class DownloadEmail(BaseModel):
    found_us_through_choices = [
        ('google', 'Google'),
        ('social_media', 'Mídias Sociais'),
        ('friend', 'Indicação de Amigo'),
        ('other', 'Outro'),
    ]

    name = models.CharField(max_length=255, verbose_name="Nome completo")
    email = models.EmailField(verbose_name="E-mail")
    found_us_through = models.CharField(
        max_length=100,
        choices=found_us_through_choices,
        verbose_name="Por onde nos encontrou?"
    )
    pack = models.ForeignKey(Pack, on_delete=models.SET_NULL, null=True, blank=True, related_name='downloads')
    registered_at = models.DateTimeField(auto_now_add=True)
    consent_for_marketing = models.BooleanField(default=False, verbose_name="Consentimento para marketing")

    def __str__(self):
        return f"{self.name} ({self.email})"

pine_studio/pine/models/pack.py
from django.db import models
from django.utils.text import slugify
from PIL import Image
from ..models._base import BaseModel
from ..models.tag import Tag


class Pack(BaseModel):
    cover = models.ImageField(upload_to='packs_covers/')
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, max_length=200)
    price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    is_free = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name='packs', blank=True)
    sales_link = models.URLField(blank=True, null=True)
    items = models.ManyToManyField('PackItem', related_name='packs', blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            truncated_name = self.name[:50]
            base_slug = slugify(truncated_name)
            slug = base_slug
            num = 1

            while Pack.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{num}"
                num += 1
            self.slug = slug[:50]

        super().save(*args, **kwargs)


class PackItem(BaseModel):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

pine_studio/pine/forms/contact.py
from django import forms
from ..models import DownloadEmail, Pack
from ..models.contact import ContactMessage


class DownloadEmailForm(forms.ModelForm):
    class Meta:
        model = DownloadEmail
        fields = ['name', 'email', 'found_us_through', 'pack', 'consent_for_marketing']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'w-full text-gray-800 px-4 py-2 rounded-md focus:outline-none',
                'placeholder': 'Digite seu nome'}),
            'email': forms.EmailInput(attrs={
                'class': 'w-full text-gray-800 px-4 py-2 rounded-md focus:outline-none',
                'placeholder': 'Digite seu e-mail'}),
            'found_us_through': forms.Select(attrs={
                'class': 'w-full text-black px-4 py-2 rounded-md focus:outline-none'}),
            'consent_for_marketing': forms.CheckboxInput(attrs={
                'class': 'form-check-input text-blue-600 border-gray-300 rounded cursor-pointer'}),
        }
    
    def __init__(self, *args, **kwargs):
        pack = kwargs.pop('pack', None)
        super().__init__(*args, **kwargs)

        if pack:
            self.fields['pack'].initial = pack
            self.fields['pack'].queryset = Pack.objects.filter(id=pack.id)


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'phone', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'w-full px-4 py-2 border rounded-lg focus:outline-none focus:border-indigo-500'}),
            'email': forms.EmailInput(attrs={'class': 'w-full px-4 py-2 border rounded-lg focus:outline-none focus:border-indigo-500'}),
            'phone': forms.TextInput(attrs={'class': 'w-full px-4 py-2 border rounded-lg focus:outline-none focus:border-indigo-500'}),
            'subject': forms.TextInput(attrs={'class': 'w-full px-4 py-2 border rounded-lg focus:outline-none focus:border-indigo-500'}),
            'message': forms.Textarea(attrs={'class': 'w-full px-4 py-2 border rounded-lg focus:outline-none focus:border-indigo-500', 'rows': 4}),
        }

pine_studio/pine/views/about.py
from django.views.generic import TemplateView


class AboutPageView(TemplateView):
    template_name = 'front/about.html'

pine_studio/pine/views/contact.py
from django.views.generic import TemplateView, ListView
from django.http import JsonResponse
from django.shortcuts import redirect
from django.contrib import messages
from ..forms.contact import ContactForm
from ..views.email_management import EmailManagementView


class ContactView(TemplateView):
    template_name = 'front/contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ContactForm()
        return context
    
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)

        if form.is_valid():
            contact_message = form.save()

            subject = f"Nova mensagem de {contact_message.name} - {contact_message.subject}"
            context = {
                'name': contact_message.name,
                'email': contact_message.email,
                'phone': contact_message.phone,
                'subject': contact_message.subject,
                'message': contact_message.message
            }

            template_name = 'email/contact_email.html'
            to_emails = ['contatopinestudio@gmail.com']
            email_sent = EmailManagementView.send_email(subject, template_name, context, to_emails)

            if email_sent:
                messages.success(request, 'Mensagem enviada com sucesso!')
                return redirect('contact')

            else:
                messages.error(request, 'Falha ao enviar o e-mail.')
                return redirect('contact')

        return JsonResponse({'status': 'error', 'message': 'Dados inválidos.'}, status=400)

pine_studio/pine/views/home.py
from django.views.generic import ListView
from ..models import Creative


class HomeView(ListView):
    template_name = 'front/home.html'
    context_object_name = 'creatives'

    def get_queryset(self):
        return Creative.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)   
        context['featured_free_creatives'] = Creative.objects.filter(is_featured=True)
        return context

pine_studio/pine/views/pack.py
from django.contrib import messages
from django.http import JsonResponse
from .email_management import EmailManagementView
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.db.models import Q
from ..models import Pack
from ..forms.contact import DownloadEmailForm


class PackListView(ListView):
    model = Pack
    template_name = 'front/packs.html'
    context_object_name = 'packs'
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        queryset = Pack.objects.all().order_by('-update_at')

        is_free = self.request.GET.get('is_free')
        if is_free == "true":
            queryset = queryset.filter(is_free=True)
        elif is_free == "false":
            queryset = queryset.filter(is_free=False)

        if query:
            queryset = queryset.filter(Q(name__icontains=query) | Q(description__icontains=query))

        return queryset


class PackDetailView(DetailView):
    model = Pack
    template_name = 'front/pack_detail.html'
    context_object_name = 'pack'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pack = self.object

        context['creatives_1080x1080'] = pack.creatives.filter(dimensions="1080x1080").exclude(carousels__isnull=False).order_by('created_at')
        context['creatives_1080x1350'] = pack.creatives.filter(dimensions="1080x1350").exclude(carousels__isnull=False).order_by('created_at')
        context['creatives_1080x1920'] = pack.creatives.filter(dimensions="1080X1920").exclude(carousels__isnull=False).order_by('created_at')
        
        creatives_with_carousels_square = {}
        creatives_with_carousels_vertical = {}

        creatives = pack.creatives.filter(carousels__isnull=False)
        for creative in creatives:
            carousels = list(creative.carousels.all())
            
            if creative.dimensions == '1080x1080':
                creatives_with_carousels_square[creative] = carousels
            elif creative.dimensions == '1080x1350':
                creatives_with_carousels_vertical[creative] = carousels

        context['creatives_carousels_square'] = creatives_with_carousels_square
        context['creatives_carousels_vertical'] = creatives_with_carousels_vertical
        
        context['form'] = DownloadEmailForm(pack=self.object)
        
        return context

    def post(self, request, *args, **kwargs):
        form = DownloadEmailForm(request.POST)
        pack = self.get_object()

        if form.is_valid():
            download_email = form.cleaned_data

            subject = f"Pack {download_email['pack'].name}"
            context = {
                'name': download_email['name'],
                'pack_name': download_email['pack'].name if download_email['pack'] else 'Pacote não especificado',
                'pack_link': download_email['pack'].sales_link
            }

            template_name = 'email/free_pack_email.html'
            to_emails = [download_email['email']]
            email_sent = EmailManagementView.send_email(subject, template_name, context, to_emails)

            if email_sent:
                form.save()
                messages.success(request, 'O pack foi enviado com sucesso para o seu e-mail! Verifique sua caixa de entrada e, se necessário, a pasta de spam')
                return redirect('pack_detail', slug=pack.slug)
            else:
                messages.error(request, 'Falha ao enviar o e-mail. Por favor, entre em contato conosco')
                return redirect('pack_detail', slug=pack.slug)

        return JsonResponse({'status': 'error', 'message': 'Dados inválidos.'}, status=400)

pine_studio/templates/front/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

    Quem sou eu?

{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<div class="flex-grow content container mx-auto mb-8 mt-28 flex flex-col justify-center items-center">
    <section class="flex flex-col lg:flex-row items-center lg:space-x-8 lg:space-y-0 p-0 px-6 md:px-0 md:p-6">
        <div class="flex flex-col items-center gap-4 w-1/3">
            <div class="relative w-72 h-72 md:w-[28rem] md:h-[28rem] rounded-full overflow-hidden">
                <img src="{% static 'assets/eu.jpg' %}" alt="Foto de Rafael" class="w-full h-full object-cover object-center">
            </div>
        </div>

        <div class="flex-1 flex flex-col gap-4 p-4 text-lg text-gray-700 leading-relaxed">
            <h1 class="text-4xl text-center md:text-start md:text-5xl leading-tight" style="color: white; font-family: 'Piepie W01 Regular', sans-serif;">Quem sou eu?</h1>
            <p style="color: var(--secondary-color-light);">
                Olá! Meu nome é Rafael Pinheiro, e minha jornada é guiada pela criatividade e pela paixão por transformar ideias em realidade. Comecei e continuo minha trajetória atuando na igreja, aprendendo a usar programas e técnicas para criar artes e vídeos que dão vida às mensagens e eventos. Foi nesse ambiente que desenvolvi meu olhar criativo e descobri o impacto do design em conectar pessoas e transmitir mensagens de forma poderosa.

                Hoje, trabalho como desenvolvedor, unindo minha bagagem artística com habilidades técnicas para criar soluções criativas e funcionais. Já tive a oportunidade de desenvolver designs para diversas páginas, sempre buscando um equilíbrio perfeito entre estética e usabilidade.
                
                Meu objetivo vai além de criar; desejo também colaborar para que outros possam alcançar designs de alto nível. Seja por meio de um código bem estruturado, de uma arte impactante ou do compartilhamento de conhecimento, acredito que cada projeto é uma oportunidade de aprendizado, inovação e de deixar uma marca positiva no mundo.
            </p>
        </div>
    </section>
</div>
{% endblock %}

pine_studio/templates/front/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Contato
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'front/contact_style.css' %}">
{% endblock %}

{% block content %}
    <div class="flex-grow container mx-auto mb-8 mt-28 flex flex-col items-center px-4 sm:px-6 lg:px-8">
        {% if messages %}
            <div class="w-full mt-4">
                <ul class="space-y-2">
                    {% for message in messages %}
                        <li class="p-4 rounded-lg text-center 
                            {% if message.tags == 'success' %} bg-green-100 text-green-700 {% endif %} 
                            {% if message.tags == 'error' %} bg-red-100 text-red-700 {% endif %}">
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <section class="py-6 w-full flex flex-col justify-center items-center">
            <header class="text-center mb-4">
                <h1 class="text-3xl md:text-5xl text-white" style="color: var(--tertiary-color-light); font-family: 'Piepie W01 Regular', sans-serif;">
                    Entre em Contato Conosco
                </h1>
                <p class="text-sm sm:text-base lg:text-lg text-white mt-2 px-4 md:px-0">
                    Estamos aqui para tirar suas dúvidas e ouvir suas sugestões!
                </p>
            </header>

            <form id="contact-form" action="{% url 'contact' %}" method="POST" class="w-full md:w-1/2 py-6 px-2 rounded-lg">
                {% csrf_token %}
                {{ form.non_field_errors }}

                <div class="mb-4">
                    <label for="name" class="block text-sm text-white mb-2">Seu Nome</label>
                    {{ form.name }}
                </div>

                <div class="mb-4">
                    <label for="email" class="block text-sm text-white mb-2">Seu E-mail</label>
                    {{ form.email }}
                </div>

                <div class="mb-4">
                    <label for="phone" class="block text-sm text-white mb-2">Seu Telefone</label>
                    {{ form.phone }}
                </div>

                <div class="mb-4">
                    <label for="subject" class="block text-sm text-white mb-2">Assunto</label>
                    {{ form.subject }}
                </div>

                <div class="mb-4">
                    <label for="message" class="block text-sm text-white mb-2">Mensagem</label>
                    {{ form.message }}
                </div>

                <div>
                    <button type="submit" id="submit-button" class="default-button w-full px-4 py-2 rounded-lg transition duration-200" style="background-color: var(--tertiary-color); color: var(--secondary-color-light);">
                        Enviar
                    </button>
                </div>
            </form>
        </section>
    </div>    

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script>
        $(document).ready(function() {
            $('#contact-form').on('submit', function() {
                $('#submit-button').prop('disabled', true);
            });
        });
    </script>
{% endblock %}

pine_studio/templates/front/pack_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ pack.name }}
{% endblock %}

{% block content %}

<div class="flex-grow content container mx-auto mb-8 mt-28 flex flex-col justify-center items-center px-4">
    <div class="messages-container">
        {% if messages %}
            <div class="flex justify-center items-center mb-6 w-full">
                {% for message in messages %}
                    <div class="message text-center p-4 mb-4 w-full text-white rounded-md
                        {% if message.tags == 'error' %} bg-red-500 {% endif %}"
                        style="{% if message.tags == 'success' %} background-color: var(--subcolor-dark);{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <div class="flex flex-col mb-12 gap-4">
        <div class="flex flex-wrap md:flex-nowrap">
            <div class="flex-shrink-0 w-full md:w-1/2 mb-4 md:mb-0 md:mr-6">
                <div class="relative h-full w-full pt-[56.25%] rounded-md shadow-md overflow-hidden">
                    <img src="{{ pack.cover.url }}" alt="{{ pack.name }}" class="absolute inset-0 w-full h-full object-cover" />
                </div>
            </div>
            <div class="flex flex-col gap-4 w-full md:w-1/2 justify-center p-4">
                <div class="flex flex-col gap-4 md:gap-0 md:flex-row justify-between items-center md:items-end">
                    <h1 class="text-5xl text-center md:text-left text-gray-900" style="color: var(--secondary-color-light); font-family: 'Piepie W01 Regular', sans-serif;">{{ pack.name }}</h1>
                    <h1 class="text-xl text-center md:text-right md:text-3xl text-gray-900 w-1/3" 
                        style="color: var(--tertiary-color-light); font-family: 'Montserrat', sans-serif;">
                        {% if pack.price %}
                            R$ <b>{{ pack.price }}</b>
                        {% else %}
                            Grátis
                        {% endif %}
                    </h1>
                </div>
                <p class="text-base md:text-lg text-white">{{ pack.description }}</p>
                <div class="flex flex-col gap-2 md:gap-0">
                    <h1 class="text-lg md:text-xl text-gray-900" style="color: var(--tertiary-color-light); font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">Itens <b>Inclusos:</b></h1>
                    <div class="gap-4 hidden md:flex">
                        {% for item in pack.items.all %}
                            <div class="text-lg border-b-2 border-dashed" 
                            style="color: var(--secondary-color-light-opacity); border-color: var(--secondary-color-light-opacity) !important; 
                                        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
                                {{ item.name }}
                            </div>
                        {% empty %}
                            <div class="text-lg border-b-2 border-dashed pb-2" 
                                style="color: var(--secondary-color-light-opacity); border-color: var(--secondary-color-light-opacity) !important; 
                                        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
                                Nenhum item vinculado.
                            </div>
                        {% endfor %}
                    </div>
                    <div class="md:hidden grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-auto gap-4">
                        {% for item in pack.items.all %}
                            <div class="text-lg border-b-2 border-dashed pb-2"
                                 style="color: var(--secondary-color-light-opacity); border-color: var(--secondary-color-light-opacity) !important; 
                                        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
                                {{ item.name }}
                            </div>
                        {% empty %}
                            <div class="text-lg border-b-2 border-dashed pb-2" 
                                 style="color: var(--secondary-color-light-opacity); border-color: var(--secondary-color-light-opacity) !important; 
                                        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
                                Nenhum item vinculado.
                            </div>
                        {% endfor %}
                    </div>                    
                </div>
            </div>
        </div>
        {% if pack.is_free %}
            <div 
                class="rounded-lg text-center cursor-pointer py-4 open-modal-pack" 
                style="background-color: var(--tertiary-color); color: var(--secondary-color-light);"
                data-modal-id="freePackModal">
                Obter <b>Gratuitamente</b>
            </div>
        {% else %}
            <a href="{{ pack.sales_link }}" target="_blank">
                <div 
                    class="rounded-lg text-center cursor-pointer py-4" 
                    style="background-color: var(--tertiary-color); color: var(--secondary-color-light);">
                    Adquira <b>agora!</b>
                </div>
            </a>
        {% endif %}
    </div>

    <div id="freePackModal" class="hidden fixed inset-0 bg-gray-800 bg-opacity-50 flex justify-center items-center z-50 cursor-pointer">
        <div class="bg-white flex flex-col gap-8 p-8 rounded-lg w-11/12 sm:w-3/4 md:w-1/2 lg:w-1/3 xl:w-1/4 flex flex-col items-center" style="background-color: var(--primary-color);">
            <h2 class="text-3xl text-white text-center">Obtenha este <b>Pack Gratuitamente</b></h2>
            
            <form method="POST" class="flex flex-col gap-2">
                {% csrf_token %}
                {{ form.non_field_errors }}
                
                <div class="flex flex-col">
                    <label for="id_name" class="text-white mb-2">Nome completo</label>
                    {{ form.name }}
                </div>
            
                <div class="flex flex-col">
                    <label for="id_email" class="text-white mb-2">E-mail</label>
                    {{ form.email }}
                </div>
            
                <div class="flex flex-col">
                    <label for="id_found_us_through" class="text-white mb-2">Por onde nos encontrou?</label>
                    {{ form.found_us_through }}
                </div>

                <div hidden>
                    {{ form.pack }}
                </div>
            
                <div class="flex gap-2 items-center justify-center">
                    <label for="id_consent_for_marketing" class="text-white">Concordo em receber materiais de marketing</label>
                    {{ form.consent_for_marketing }}
                </div>
            
                <button type="submit" class="w-full text-white px-4 py-2 rounded-md transition duration-300" style="background-color: var(--subcolor-dark);">
                    Enviar
                </button>
            </form>            
        </div>
    </div>

    <div class="flex flex-col justify-center items-center gap-8">
        {% if creatives_1080x1350 %}
            <div class="w-full">
                <h2 class="text-2xl mb-4" style="color: var(--tertiary-color-light);">Posts <b>Verticais</b></h2>
                <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                    {% for creative in creatives_1080x1350 %}
                        <div class="aspect-w-1 aspect-h-1 rounded-md shadow-lg overflow-hidden">
                            <img src="{{ creative.image.url }}" class="w-full h-full object-cover cursor-pointer open-modal"/>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if creatives_1080x1080 %}
            <div class="w-full">
                <h2 class="text-2xl mb-4" style="color: var(--tertiary-color-light);">Posts <b>Quadrados</b></h2>
                <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                    {% for creative in creatives_1080x1080 %}
                        <div class="aspect-w-1 aspect-h-1 rounded-md shadow-lg overflow-hidden">
                            <img src="{{ creative.image.url }}" class="w-full h-full object-cover cursor-pointer open-modal"/>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    
        {% if creatives_1080x1920 %}
            <div class="w-full">
                <h2 class="text-2xl mb-4" style="color: var(--tertiary-color-light);">Stories</h2>
                <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                    {% for creative in creatives_1080x1920 %}
                        <div class="aspect-w-1 aspect-h-1 rounded-md shadow-lg overflow-hidden">
                            <img src="{{ creative.image.url }}" class="w-full h-full object-cover cursor-pointer open-modal"/>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    
        {% if creatives_carousels_square %}
            <div class="w-full">
                <h2 class="text-2xl mb-4" style="color: var(--tertiary-color-light);">Carrosséis <b>Quadrados</b></h2>
                {% for creative, carousels in creatives_carousels_square.items %}
                    <div class="mb-6">
                        <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                            <div class="aspect-w-1 aspect-h-1 rounded-md shadow-lg overflow-hidden">
                                <img src="{{ creative.image.url }}" class="w-full h-full object-cover cursor-pointer open-modal"/>
                            </div>
                            {% for carousel in carousels %}
                                <div class="aspect-w-1 aspect-h-1 rounded-md shadow-lg overflow-hidden">
                                    <img src="{{ carousel.image.url }}" class="w-full h-full object-cover cursor-pointer open-modal"/>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% if creatives_carousels_vertical %}
            <div class="w-full">
                <h2 class="text-2xl mb-4" style="color: var(--tertiary-color-light);">Carrosséis <b>Verticais</b></h2>
                {% for creative, carousels in creatives_carousels_vertical.items %}
                    <div class="mb-6">
                        <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                            <div class="aspect-w-1 aspect-h-1 rounded-md shadow-lg overflow-hidden">
                                <img src="{{ creative.image.url }}" class="w-full h-full object-cover cursor-pointer open-modal"/>
                            </div>
                            {% for carousel in carousels %}
                                <div class="aspect-w-1 aspect-h-1 rounded-md shadow-lg overflow-hidden">
                                    <img src="{{ carousel.image.url }}" class="w-full h-full object-cover cursor-pointer open-modal"/>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <div id="image-modal" class="fixed inset-0 bg-black bg-opacity-75 flex justify-center items-center hidden px-4 md:px-0" style="z-index: 999; cursor: pointer;">
        <img id="modal-image" class="w-[35rem] max-w-full max-h-full rounded-md" alt="Imagem ampliada">
    </div>
</div>

<script>
    $(document).ready(function () {
        $(".open-modal").on("click", function () {
        const imageUrl = $(this).attr("src");
        $("#modal-image").attr("src", imageUrl);
        $("#image-modal").removeClass("hidden").addClass("flex");
    });

    $("#image-modal").on("click", function (e) {
        if ($(e.target).is("#image-modal")) {
            $(this).removeClass("flex").addClass("hidden");
        }
    });

    $(document).on("keydown", function (e) {
        if (e.key === "Escape" || e.keyCode === 27) {
            $("#image-modal").addClass("hidden");
        }
    });

    $('.open-modal-pack').on('click', function () {
        const modalId = $(this).data('modal-id');
        $('#' + modalId).removeClass('hidden');
    });

    $('.close-modal').on('click', function () {
        $(this).closest('.fixed').addClass('hidden');
    });

    $('#freePackModal').on('click', function (e) {
        if ($(e.target).is('#freePackModal')) {
            $(this).addClass('hidden');
        }
    });

    setTimeout(function () {
        $('.message').fadeOut(500);
    }, 5000)
    });
</script>

{% endblock %}